### ISSUE TITLE
Possible race when connecting with Kafka/ZK (while Kafka/ZK are booting)

### ISSUE THREAD

**Issue by jotto** [oleksiyk/kafka#49]
If I have a docker-compose configuration that has 3 containers I can reproduce a connection issue where `nokafkaclient` can't subscribe to anything:

```yml
services:
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "2181:2181"
  kafka:
    image: "kafka:latest"
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
  nokafkaclient:
    depends_on:
      - "zookeeper"
      - "kafka"
```

(the "depends_on" feature of docker-compose doesn't introduce delays or "waits", all it does is control order)

If `docker-compose up nokafkaclient` is run, the simple consumer's `init`'s promise returns successfully, yet calling `subscribe` promise returns an error:

> This request is for a topic or partition that does not exist on this broker.

* despite the existence of that topic
* and even with the `logLevel` at 5, there's no debug output at all
* no amount of time passing auto resolves the issue

restarting the `nokafkaclient` will resolve it.

If using the simple consumer, should the metadata be manually refreshed at certain times, events or errors?
